### ISSUE TITLE
Not an issue - a thank you for this guide

### ISSUE THREAD

**Issue by thiagoveloso** [jimpalompa/OpenCore-Gigabyte-Z370n-Wifi#5]
@jimpalompa thank you for this excellent guide. It is by far the best one I have seen for the Z370N WiFi. I am sure my system is running faster and smoother than ever.

There were only a few points that I was left wondering how to do:
1. replacing your bluetooth driver with one that is compatible with my Broadcom card; and
2. adding a more beautiful boot menu to Opencore

However, it took me only like half an hour to figure out those points by myself.

Apart from that, overall excellent and I am very grateful!

**Comment by jimpalompa** [comment]
Hi, please post this under **Discussions** instead and I will try to answer you ; )
